# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(blank=True, max_length=32, null=True)),
                ('dt_field', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
